'use strict'


const path = require("path")
const destDir = path.resolve(__dirname, "dist")

const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
    'entry': {
        index: './app/entry.js'
    },
    output: {
        filename: "bundle.js",
        path: destDir
    },

    plugins: [
        new HtmlWebpackPlugin({
            title: "Sample html generated by webpack HTML plugin"
        }) 
    ]
}

